"""empty message

Revision ID: ceaef613745e
Revises: 
Create Date: 2023-02-23 16:47:36.515178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceaef613745e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('artist_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('artist_id')
    )
    op.create_table('artist_mbtag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.String(length=20), nullable=False),
    sa.Column('mbtag', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.artist_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.String(length=20), nullable=False),
    sa.Column('term', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.artist_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_term')
    op.drop_table('artist_mbtag')
    op.drop_table('artist')
    # ### end Alembic commands ###
